### ISSUE TITLE
iPad doesn't load webpages with proxy (gives error),computer does

### ISSUE THREAD

**Issue by TheMetaPirate** [Athlon1600/php-proxy#2]
Hi, first of all thanks for building the proxy!

Well, I am running the latest proxy uptodate but as it says in the title it doesn't work with iPads (tested out on many) it gives me this error: http://i.imgur.com/9LuEgC4.jpg . I'm asking since my friends like your proxy more than glypes one and yours did run on an older version that I don't have anymore

I'm running it on a Raspberry Pi B+:

Link: colesinbloqueo.wtf.im/lol3/ That link is temporarly.

Thanks :3

**Comment by Athlon1600** [comment]
Is this only for YouTube?

**Comment by TheMetaPirate** [comment]
No, only for https:// sites,

**Comment by TheMetaPirate** [comment]
Update,

I looked at your https://www.php-proxy.com/test/php-proxy/ (test proxy) and it also doesn't work, http domains still work fine.

**Comment by Athlon1600** [comment]
yup just found what the problem was. download the new version and it should work now

**Comment by TheMetaPirate** [comment]
Nop, still same

**Comment by TheMetaPirate** [comment]
Yes, I just testes everything, still doesn't work with https websites, everything else is ok

**Comment by Athlon1600** [comment]
I just tested using this:
http://ipadpeek.com/

Are you installing php-proxy through composer?

**Comment by TheMetaPirate** [comment]
Yes, always

**Comment by Athlon1600** [comment]
^ that could be the problem. The way it is setup right now, composer is still downloading the old version instead of the new.

Run this instead:
composer create-project athlon1600/php-proxy**:dev-master** /var/www/

**Comment by TheMetaPirate** [comment]
Could you also put the your new version on your test site?

**Comment by Athlon1600** [comment]
This always has the latest version installed:
https://www.php-proxy.com/php-proxy/

**Comment by TheMetaPirate** [comment]
Well, I just test your website and it didn't work, Ima set up my proxy now

**Comment by TheMetaPirate** [comment]
Ok! it seems to be working!, but one thing, youtube does load in frame,but not the content.

Heres a picture: http://i.imgur.com/jBTjOvE.jpg

**Comment by Athlon1600** [comment]
ok I just added a fix. download the new version and try then

**Comment by TheMetaPirate** [comment]
Dude, thanks for all your support! You are amazing! I hope you add a donation button, If I'll get into some money, I'll sure donate it.

Btw, add composer create-project athlon1600/php-proxy:dev-master /var/www/ to your main page,
and, I'm running your pac file, from proxynova to surf, that also works really good.

If I find anything important,I'll sure to post any issues here.

**Comment by TheMetaPirate** [comment]
YouTube problem,(not only iDevices),some videos just don't load: example: http://i.imgur.com/ZWRqj6a.png

http://colesinbloqueo.wtf.im/proxtube/index.php?q=aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj01WFI3bmFaX3paQQ

**Comment by Athlon1600** [comment]
fixed:
https://www.php-proxy.com/php-proxy/index.php?q=aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj01WFI3bmFaX3paQQ

**Comment by TheMetaPirate** [comment]
Fun fact, the html5 player does not work with music videos, I have no idea how you managed to do that xD.

Btw, some components of YT don't load, aka pictures basically: http://i.imgur.com/FfNBMyi.jpg
http://i.imgur.com/Rknu3CG.jpg < (It doesn't look like that normally,I just made it smaller with my hands and took the pic) on PC works fine
